name: lexigo
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none
environment:
  sdk: ^3.5.0

dependencies:
  liquid_glass_renderer: ^0.1.1-dev.9
  auto_route: ^7.5.0
  camera: ^0.11.1
  cupertino_icons: ^1.0.2
  deep_pick: ^1.0.0
  dio: ^5.2.1+1
  emoji_picker_flutter: ^4.3.0
  envied: ^0.5.2
  equatable: ^2.0.5
  file_picker: ^10.1.9
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.6
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.15
  flutter_dotenv: ^5.0.2
  flutter_gen_runner: ^5.10.0
  flutter_inappwebview: ^6.1.5
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.1.0
  flutter_tts: ^4.2.3
  fluttertoast: ^8.2.12
  freezed_annotation: ^2.2.0
  google_fonts: ^6.2.1
  html: ^0.15.6
  http: ^1.4.0
  image: ^4.0.17
  infinite_scroll_pagination: ^4.0.0
  intl: any
  json_annotation: ^4.8.1
  liquid_glass: ^0.0.2
  meta: ^1.9.1
  path_provider: ^2.1.5
  percent_indicator: ^4.2.5
  permission_handler: ^12.0.0+1
  record: ^6.0.0
  retrofit: ^4.4.2
  retrofit_generator: ^9.2.0
  riverpod_annotation: ^2.1.1
  shared_preferences: ^2.1.2
  translator: ^1.0.3+1
  uuid: ^4.5.1
  very_good_analysis: ^7.0.0
  waveform_flutter: ^1.2.0

dev_dependencies:
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.5
  envied_generator: ^0.5.2
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21

  # Cấu hình cho adaptive icon Android (có background)
  adaptive_icon_background: "#6366F1" # Màu nền cho adaptive icon
  adaptive_icon_foreground: "assets/icons/logo.png" # Logo foreground

  web:
    generate: true
    image_path: "assets/icons/logo.png"
    background_color: "#6366F1"
    theme_color: "#6366F1"
  windows:
    generate: true
    image_path: "assets/icons/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/logo.png"

# Cập nhật splash screen với màu nền icon mới
flutter_native_splash:
  color: "#6366F1"
  image: assets/icons/logo.png

  android_12:
    image: assets/icons/logo.png
    color: "#6366F1"
    icon_background_color: "#FFFFFF" # Màu nền trắng cho icon Android 12+

    # Dark mode
    color_dark: "#1F2937"
    icon_background_color_dark: "#6366F1" # Màu nền tối cho dark mode
