// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMx7fir8CPontFP5yWHdiDPzqiNwJQUL8',
    appId: '1:537191104647:android:8e450ac80ac0b3600ab822',
    messagingSenderId: '537191104647',
    projectId: 'lexigo-d1bfb',
    storageBucket: 'lexigo-d1bfb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq0ZBtKtaaBot9negl3X_lOU3rABeHvxM',
    appId: '1:537191104647:ios:165a1186809705450ab822',
    messagingSenderId: '537191104647',
    projectId: 'lexigo-d1bfb',
    storageBucket: 'lexigo-d1bfb.firebasestorage.app',
    iosBundleId: 'com.example.verygoodcore.lexigo',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJSGRNgHLxSn6cEikB1Qkh7iYL0B8OTnE',
    appId: '1:537191104647:web:31652ac1a93b99b40ab822',
    messagingSenderId: '537191104647',
    projectId: 'lexigo-d1bfb',
    authDomain: 'lexigo-d1bfb.firebaseapp.com',
    storageBucket: 'lexigo-d1bfb.firebasestorage.app',
    measurementId: 'G-FTZTJERG8P',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq0ZBtKtaaBot9negl3X_lOU3rABeHvxM',
    appId: '1:537191104647:ios:25357ed5a0f40c070ab822',
    messagingSenderId: '537191104647',
    projectId: 'lexigo-d1bfb',
    storageBucket: 'lexigo-d1bfb.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJSGRNgHLxSn6cEikB1Qkh7iYL0B8OTnE',
    appId: '1:537191104647:web:798e82307927385a0ab822',
    messagingSenderId: '537191104647',
    projectId: 'lexigo-d1bfb',
    authDomain: 'lexigo-d1bfb.firebaseapp.com',
    storageBucket: 'lexigo-d1bfb.firebasestorage.app',
    measurementId: 'G-26WJCHY46C',
  );

}